/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linedrawing;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JToggleButton;

/**
 *
 * @author Ivan Marcellino
 */
public class menu extends javax.swing.JPanel {

    /**
     * Creates new form menu
     */
    private boolean dda, bersenham, sincos, circle;

    public boolean isDda() {
        return dda;
    }

    public void setDda(boolean dda) {
        this.dda = dda;
    }

    public boolean isBersenham() {
        return bersenham;
    }

    public void setBersenham(boolean bersenham) {
        this.bersenham = bersenham;
    }

    public boolean isSincos() {
        return sincos;
    }

    public void setSincos(boolean sincos) {
        this.sincos = sincos;
    }

    public boolean isCircle() {
        return circle;
    }

    public void setCircle(boolean circle) {
        this.circle = circle;
    }
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ddaradio = new javax.swing.JRadioButton();
        bersenhamradio = new javax.swing.JRadioButton();
        sincosradio = new javax.swing.JRadioButton();
        circleradio = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 0, 0));

        ddaradio.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(ddaradio);
        ddaradio.setText("DDA Algorithm");
        ddaradio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ddaradio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ddaradio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonClicked(evt);
            }
        });

        bersenhamradio.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(bersenhamradio);
        bersenhamradio.setText("Bresenham Algorithm");
        bersenhamradio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bersenhamradio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bersenhamradio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonClicked(evt);
            }
        });

        sincosradio.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(sincosradio);
        sincosradio.setText("Circle Drawing (sin / cos)");
        sincosradio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sincosradio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        sincosradio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonClicked(evt);
            }
        });

        circleradio.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(circleradio);
        circleradio.setText("Circle Drawing");
        circleradio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        circleradio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        circleradio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sincosradio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(circleradio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bersenhamradio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ddaradio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ddaradio)
                .addGap(18, 18, 18)
                .addComponent(bersenhamradio)
                .addGap(18, 18, 18)
                .addComponent(sincosradio)
                .addGap(18, 18, 18)
                .addComponent(circleradio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonClicked(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonClicked
        // TODO add your handling code here:
        JRadioButton t= (JRadioButton)evt.getSource();
        dda=false;
        bersenham=false;        
        sincos=false;
        circle=false;
        if (t.equals(ddaradio)){
            dda=true;
        } else if (t.equals(bersenhamradio)){
            bersenham=true;
        } else if (t.equals(circleradio)){
            circle=true;
        } else if (t.equals(sincosradio)){
            sincos=true;
        }
        ((window)(this.getParent().getParent().getParent().getParent())).resetCount();
    }//GEN-LAST:event_radioButtonClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bersenhamradio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton circleradio;
    private javax.swing.JRadioButton ddaradio;
    private javax.swing.JRadioButton sincosradio;
    // End of variables declaration//GEN-END:variables
}
